# .github/workflows/main.yml
name: Build Game

on:
  pull_request:
    types:
     — opened
    branches:
     — develop
    paths:
     — 'Assets/**'
     — 'Packages/**'
     — 'ProjectSettings/**'
  workflow_dispatch:
    inputs:
      workflow_mode:
        description: '[release] [StandaloneWindows64]'
        required: false
        default: ''
jobs:
# Job #1
  buildWithWindows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Cache
      - uses: actions/cache@v3.3.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: Build
          path: build
