# .github/workflows/main.yml
name: Build Unity Game

on:
  pull_request:
    types:
     — opened
    branches:
     — develop
    # Commented for now, update this workflow to only trigger the buildnig step when files
    # in below folders are updated. This can be done by doing a git diff and grep within
    # this workflow.
    # paths:
    #  — 'Assets/**'
    #  — 'Packages/**'
    #  — 'ProjectSettings/**'
  workflow_dispatch:

jobs:
  buildWithWindows:
    name: Build for WindowsOS
    runs-on: ubuntu-latest # using windows-latest causes an issue with the docker image that unityci uses
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build Unity project
        uses: game-ci/unity-builder@v3.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      # Output
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FocusBreakout-build-dev
          path: build
